#builds everyting and stores it to dist folder
version: '2'

services:
  indigo-lucene-builder:
    build:
      context: ../
      dockerfile : docker/Dockerfile-builder
    volumes:
      - .:/indigo-lucene
      - ./.m2/:/root/.m2
      - ./dist/:/dist

#builds only chem-query plugin
  chem-query-builder:
    extends: indigo-lucene-builder
    command: bash build-chem-query.sh

  indigo-lucene-prod:
    build:
      context: ../
      dockerfile: docker/Dockerfile-prod
    ports:
      - "8983:8983"
    environment:
      - SOLR_STARTUP_PARAMS=-m 2g
    command: bash /opt/solr/startup.sh

  indigo-lucene-dev:
    build: 
      context: ../
      dockerfile: docker/Dockerfile-debug
    ports:
      - "8983:8983"
      - "8787:8787"
      - "6900:6900"
      - "8282:8080"
    environment:
      - SOLR_STARTUP_PARAMS=-a -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=6900 -m 2g
    command: bash /opt/solr/startup.sh
    volumes:
      - ../dist:/opt/solr/plugin
      - ../conf:/opt/solr/conf

#indigo-lucene-dev-fresh:
#   extends: indigo-lucene-dev
#   volumes_from:
#      - chem-query-builder
#   environment:
#     - WAIT_FOR_CHEMQUERY_BUILD=true



