version: '2'

services:
  webservice-demo:
    depends_on:
      - solr-demo
      - webservice-builder
    build:
      context: ../
      dockerfile: webservice/docker/Dockerfile-demo-webservice
    volumes:
      - ../webservice/dist/:/dist
      - ../chem-data/:/chem-data
    ports:
      - 8080:8080
    command: bash deploy-webservice-demo.sh
  solr-demo:
    depends_on:
      - plugin-builder
    build:
      context: ../
      dockerfile: docker/Dockerfile-demo-solr
    environment:
      - SOLR_STARTUP_PARAMS=-a -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=6900 -m 2g
    volumes:
      - ../../dist/:/opt/solr/plugin
      - ../conf:/opt/solr/conf
    ports:
      - 8983:8983
      - 6900:6900
  plugin-builder:
    build:
      context: ../../
      dockerfile: docker/Dockerfile-builder
    volumes:
      - ../../dist/:/dist
      - ../../:/indigo-lucene
      # - ../../.m2/:/root/.m2
    command: bash build-chem-query.sh /dist/tmp-ws
  webservice-builder:
    build:
      context: ../../
      dockerfile: demo/webservice/docker/Dockerfile-webservice-builder
    volumes:
      - ../../:/src
      - ../webservice/dist:/dist
      # - ../../.m2/:/root/.m2