language: cpp
dist: trusty
sudo: required
compiler: clang
os:
  - linux
branches:
  only:
  - master
before_script:
  - sudo apt-get update -qq && sudo apt-get install -y libfreetype6-dev libfontconfig1-dev python
script:
  - python build_scripts/indigo-release-libs.py
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/66027894f79a647d01ef
    on_success: change
    on_failure: always
    on_start: never
