language: cpp
dist: trusty
sudo: required
compiler: clang
os:
  - linux
  - osx
branches:
  only:
  - master
before_script:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq && sudo apt-get install -y libfreetype6-dev libfontconfig1-dev python gcc-6 g++-6 && sudo ln -fs /usr/bin/gcc-6 /usr/bin/gcc && sudo ln -fs /usr/bin/g++-6 /usr/bin/g++; fi
script:
  - python build_scripts/indigo-release-libs.py
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/66027894f79a647d01ef
    on_success: change
    on_failure: always
    on_start: never
