language: cpp
dist: trusty
sudo: required
os:
  - linux
  - osx
branches:
  only:
  - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - libfreetype6-dev
    - libfontconfig1-dev
    - python
script:
  - if [ $TRAVIS_OS_NAME == linux ]; then CC=/usr/bin/gcc-6 CXX=/usr/bin/g++-6 python build_scripts/indigo-release-libs.py; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then python build_scripts/indigo-release-libs.py; fi
  - python build_scripts/indigo-make-by-libs.py --type=python
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/$INDIGO_GITTER_KEY
    on_success: change
    on_failure: always
    on_start: never
